export { default as TestSlice } from './TestSlice'
export { default as SliceTwo } from './SliceTwo'
export { default as HeroComponent } from './HeroComponent'
export { default as RichText } from './RichText'
export { default as GroupPages } from './GroupPages'